sudo: False
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
script: "pyb -X && PYTHONPATH=src/main/python src/main/scripts/analyze"
after_success:
  - coveralls --verbose
